export interface MockModel {
  id: string;
  name: string;
  provider: string;
  lab: string;
  description: string;
  contextWindow: string;
  priceInput: number; // per 1M tokens
  priceOutput: number; // per 1M tokens
  priceDisplay: string;
  rating: number;
  reviews: number;
  tags: string[];
  capabilities: string[];
  category: 'language' | 'vision' | 'code' | 'image' | 'audio' | 'multimodal';
  isOpenSource: boolean;
  isNew: boolean;
  speed: 'fast' | 'medium' | 'slow';
  maxOutputTokens: number;
  createdAt: string;
}

const now = new Date().toISOString();

export const mockModels: MockModel[] = [
  // OpenAI Models
  {
    id: 'gpt-4o',
    name: 'GPT-4o',
    provider: 'OpenAI',
    lab: 'OpenAI',
    description: 'Most advanced model with vision and reasoning. Best for enterprise applications.',
    contextWindow: '128K',
    priceInput: 2.5,
    priceOutput: 10.0,
    priceDisplay: '$2.50 / $10.00 per 1M',
    rating: 4.9,
    reviews: 2847,
    tags: ['Advanced', 'Multimodal', 'Enterprise', 'Fast'],
    capabilities: ['chat', 'vision', 'reasoning', 'tools'],
    category: 'multimodal',
    isOpenSource: false,
    isNew: false,
    speed: 'fast',
    maxOutputTokens: 16384,
    createdAt: '2024-05-13T00:00:00Z',
  },
  {
    id: 'gpt-4o-mini',
    name: 'GPT-4o mini',
    provider: 'OpenAI',
    lab: 'OpenAI',
    description: 'Efficient version of GPT-4o. Perfect for cost-sensitive applications.',
    contextWindow: '128K',
    priceInput: 0.15,
    priceOutput: 0.6,
    priceDisplay: '$0.15 / $0.60 per 1M',
    rating: 4.8,
    reviews: 1542,
    tags: ['Budget', 'Fast', 'Efficient', 'Popular'],
    capabilities: ['chat', 'vision', 'reasoning'],
    category: 'multimodal',
    isOpenSource: false,
    isNew: false,
    speed: 'fast',
    maxOutputTokens: 16384,
    createdAt: '2024-07-18T00:00:00Z',
  },
  {
    id: 'gpt-4-turbo',
    name: 'GPT-4 Turbo',
    provider: 'OpenAI',
    lab: 'OpenAI',
    description: 'Previous generation with 128K context. Good for large document analysis.',
    contextWindow: '128K',
    priceInput: 10.0,
    priceOutput: 30.0,
    priceDisplay: '$10.00 / $30.00 per 1M',
    rating: 4.7,
    reviews: 3204,
    tags: ['Powerful', 'Context', 'Analysis', 'Mature'],
    capabilities: ['chat', 'vision', 'code', 'reasoning'],
    category: 'multimodal',
    isOpenSource: false,
    isNew: false,
    speed: 'medium',
    maxOutputTokens: 4096,
    createdAt: '2023-11-06T00:00:00Z',
  },
  {
    id: 'o1',
    name: 'o1',
    provider: 'OpenAI',
    lab: 'OpenAI',
    description: 'Advanced reasoning model for complex problem solving and research.',
    contextWindow: '128K',
    priceInput: 15.0,
    priceOutput: 60.0,
    priceDisplay: '$15.00 / $60.00 per 1M',
    rating: 4.9,
    reviews: 892,
    tags: ['Reasoning', 'Research', 'Complex', 'Premium'],
    capabilities: ['reasoning', 'code', 'analysis'],
    category: 'language',
    isOpenSource: false,
    isNew: true,
    speed: 'slow',
    maxOutputTokens: 32768,
    createdAt: '2024-12-17T00:00:00Z',
  },
  {
    id: 'o1-mini',
    name: 'o1-mini',
    provider: 'OpenAI',
    lab: 'OpenAI',
    description: 'Lightweight reasoning model for faster problem solving.',
    contextWindow: '128K',
    priceInput: 3.0,
    priceOutput: 12.0,
    priceDisplay: '$3.00 / $12.00 per 1M',
    rating: 4.8,
    reviews: 614,
    tags: ['Reasoning', 'Fast', 'Efficient', 'New'],
    capabilities: ['reasoning', 'code', 'math'],
    category: 'language',
    isOpenSource: false,
    isNew: true,
    speed: 'medium',
    maxOutputTokens: 16384,
    createdAt: '2024-12-17T00:00:00Z',
  },
  {
    id: 'o3-mini',
    name: 'o3-mini',
    provider: 'OpenAI',
    lab: 'OpenAI',
    description: 'Fastest reasoning model with strong performance for everyday tasks.',
    contextWindow: '128K',
    priceInput: 1.1,
    priceOutput: 4.4,
    priceDisplay: '$1.10 / $4.40 per 1M',
    rating: 4.8,
    reviews: 521,
    tags: ['Reasoning', 'Fast', 'Practical', 'New'],
    capabilities: ['reasoning', 'code', 'analysis'],
    category: 'language',
    isOpenSource: false,
    isNew: true,
    speed: 'fast',
    maxOutputTokens: 16384,
    createdAt: '2024-12-20T00:00:00Z',
  },
  {
    id: 'dall-e-3',
    name: 'DALL-E 3',
    provider: 'OpenAI',
    lab: 'OpenAI',
    description: 'State-of-the-art image generation with exceptional quality.',
    contextWindow: '4K',
    priceInput: 0.04,
    priceOutput: 0.12,
    priceDisplay: '$0.04 / $0.12 per 1M',
    rating: 4.8,
    reviews: 2156,
    tags: ['Image', 'Creative', 'Quality', 'Professional'],
    capabilities: ['image', 'creative'],
    category: 'image',
    isOpenSource: false,
    isNew: false,
    speed: 'medium',
    maxOutputTokens: 2048,
    createdAt: '2023-10-12T00:00:00Z',
  },
  {
    id: 'whisper-v3',
    name: 'Whisper v3',
    provider: 'OpenAI',
    lab: 'OpenAI',
    description: 'Multilingual speech-to-text with high accuracy.',
    contextWindow: '32K',
    priceInput: 0.02,
    priceOutput: 0.02,
    priceDisplay: '$0.02 per 1M',
    rating: 4.9,
    reviews: 1847,
    tags: ['Audio', 'Speech', 'Multilingual', 'Accurate'],
    capabilities: ['audio', 'transcription'],
    category: 'audio',
    isOpenSource: false,
    isNew: false,
    speed: 'fast',
    maxOutputTokens: 8192,
    createdAt: '2023-03-01T00:00:00Z',
  },

  // Anthropic Models
  {
    id: 'claude-3-5-sonnet',
    name: 'Claude 3.5 Sonnet',
    provider: 'Anthropic',
    lab: 'Anthropic',
    description: 'Balanced model with strong reasoning and speed. Ideal for most applications.',
    contextWindow: '200K',
    priceInput: 3.0,
    priceOutput: 15.0,
    priceDisplay: '$3.00 / $15.00 per 1M',
    rating: 4.9,
    reviews: 3421,
    tags: ['Balanced', 'Fast', 'Long-context', 'Popular'],
    capabilities: ['chat', 'code', 'analysis', 'vision'],
    category: 'multimodal',
    isOpenSource: false,
    isNew: false,
    speed: 'fast',
    maxOutputTokens: 4096,
    createdAt: '2024-06-20T00:00:00Z',
  },
  {
    id: 'claude-3-5-haiku',
    name: 'Claude 3.5 Haiku',
    provider: 'Anthropic',
    lab: 'Anthropic',
    description: 'Fastest Anthropic model. Great for real-time applications.',
    contextWindow: '200K',
    priceInput: 0.8,
    priceOutput: 4.0,
    priceDisplay: '$0.80 / $4.00 per 1M',
    rating: 4.8,
    reviews: 1204,
    tags: ['Fast', 'Budget', 'Efficient', 'Real-time'],
    capabilities: ['chat', 'code', 'vision'],
    category: 'multimodal',
    isOpenSource: false,
    isNew: false,
    speed: 'fast',
    maxOutputTokens: 4096,
    createdAt: '2024-08-12T00:00:00Z',
  },
  {
    id: 'claude-3-opus',
    name: 'Claude 3 Opus',
    provider: 'Anthropic',
    lab: 'Anthropic',
    description: 'Most capable Claude model. Exceptional for complex reasoning.',
    contextWindow: '200K',
    priceInput: 15.0,
    priceOutput: 75.0,
    priceDisplay: '$15.00 / $75.00 per 1M',
    rating: 4.9,
    reviews: 2156,
    tags: ['Premium', 'Reasoning', 'Complex', 'Powerful'],
    capabilities: ['chat', 'code', 'reasoning', 'analysis'],
    category: 'language',
    isOpenSource: false,
    isNew: false,
    speed: 'medium',
    maxOutputTokens: 4096,
    createdAt: '2024-03-04T00:00:00Z',
  },
  {
    id: 'claude-3-sonnet',
    name: 'Claude 3 Sonnet',
    provider: 'Anthropic',
    lab: 'Anthropic',
    description: 'Previous generation balanced model. Still very capable.',
    contextWindow: '200K',
    priceInput: 3.0,
    priceOutput: 15.0,
    priceDisplay: '$3.00 / $15.00 per 1M',
    rating: 4.7,
    reviews: 1847,
    tags: ['Balanced', 'Reliable', 'Mature', 'Proven'],
    capabilities: ['chat', 'code', 'vision'],
    category: 'multimodal',
    isOpenSource: false,
    isNew: false,
    speed: 'fast',
    maxOutputTokens: 4096,
    createdAt: '2024-03-04T00:00:00Z',
  },
  {
    id: 'claude-3-haiku',
    name: 'Claude 3 Haiku',
    provider: 'Anthropic',
    lab: 'Anthropic',
    description: 'Lightweight Claude for fast inference.',
    contextWindow: '200K',
    priceInput: 0.8,
    priceOutput: 4.0,
    priceDisplay: '$0.80 / $4.00 per 1M',
    rating: 4.6,
    reviews: 923,
    tags: ['Fast', 'Budget', 'Lightweight', 'Edge'],
    capabilities: ['chat', 'vision'],
    category: 'multimodal',
    isOpenSource: false,
    isNew: false,
    speed: 'fast',
    maxOutputTokens: 4096,
    createdAt: '2024-03-04T00:00:00Z',
  },

  // Google Models
  {
    id: 'gemini-2-flash',
    name: 'Gemini 2.0 Flash',
    provider: 'Google',
    lab: 'Google DeepMind',
    description: 'Latest multimodal model with excellent speed and reasoning.',
    contextWindow: '1M',
    priceInput: 0.075,
    priceOutput: 0.3,
    priceDisplay: '$0.075 / $0.30 per 1M',
    rating: 4.9,
    reviews: 2541,
    tags: ['Fast', 'Multimodal', 'Long-context', 'New'],
    capabilities: ['chat', 'vision', 'code', 'reasoning'],
    category: 'multimodal',
    isOpenSource: false,
    isNew: true,
    speed: 'fast',
    maxOutputTokens: 8192,
    createdAt: '2024-12-19T00:00:00Z',
  },
  {
    id: 'gemini-1-5-pro',
    name: 'Gemini 1.5 Pro',
    provider: 'Google',
    lab: 'Google DeepMind',
    description: 'Professional-grade multimodal model with 2M context window.',
    contextWindow: '2M',
    priceInput: 1.25,
    priceOutput: 5.0,
    priceDisplay: '$1.25 / $5.00 per 1M',
    rating: 4.8,
    reviews: 1692,
    tags: ['Professional', 'Long-context', 'Vision', 'Enterprise'],
    capabilities: ['chat', 'vision', 'code', 'analysis'],
    category: 'multimodal',
    isOpenSource: false,
    isNew: false,
    speed: 'medium',
    maxOutputTokens: 8192,
    createdAt: '2024-05-14T00:00:00Z',
  },
  {
    id: 'gemini-1-5-flash',
    name: 'Gemini 1.5 Flash',
    provider: 'Google',
    lab: 'Google DeepMind',
    description: 'Fast multimodal model with 1M context window.',
    contextWindow: '1M',
    priceInput: 0.075,
    priceOutput: 0.3,
    priceDisplay: '$0.075 / $0.30 per 1M',
    rating: 4.7,
    reviews: 1247,
    tags: ['Fast', 'Efficient', 'Long-context', 'Budget'],
    capabilities: ['chat', 'vision', 'code'],
    category: 'multimodal',
    isOpenSource: false,
    isNew: false,
    speed: 'fast',
    maxOutputTokens: 8192,
    createdAt: '2024-05-14T00:00:00Z',
  },
  {
    id: 'gemini-ultra',
    name: 'Gemini Ultra',
    provider: 'Google',
    lab: 'Google DeepMind',
    description: 'Most powerful Google model with advanced reasoning capabilities.',
    contextWindow: '256K',
    priceInput: 2.0,
    priceOutput: 8.0,
    priceDisplay: '$2.00 / $8.00 per 1M',
    rating: 4.8,
    reviews: 958,
    tags: ['Premium', 'Reasoning', 'Powerful', 'Advanced'],
    capabilities: ['chat', 'reasoning', 'code', 'analysis'],
    category: 'language',
    isOpenSource: false,
    isNew: false,
    speed: 'medium',
    maxOutputTokens: 4096,
    createdAt: '2024-03-01T00:00:00Z',
  },
  {
    id: 'gemma-2',
    name: 'Gemma 2',
    provider: 'Google',
    lab: 'Google DeepMind',
    description: 'Open-source efficient language model.',
    contextWindow: '8K',
    priceInput: 0.0,
    priceOutput: 0.0,
    priceDisplay: 'Free (open-source)',
    rating: 4.5,
    reviews: 487,
    tags: ['Open-source', 'Efficient', 'Community', 'Free'],
    capabilities: ['chat', 'code'],
    category: 'language',
    isOpenSource: true,
    isNew: false,
    speed: 'fast',
    maxOutputTokens: 4096,
    createdAt: '2024-06-27T00:00:00Z',
  },

  // Meta Models
  {
    id: 'llama-3-3-70b',
    name: 'Llama 3.3 70B',
    provider: 'Meta',
    lab: 'Meta AI',
    description: 'Latest open-source model with strong performance across benchmarks.',
    contextWindow: '8K',
    priceInput: 0.59,
    priceOutput: 0.79,
    priceDisplay: '$0.59 / $0.79 per 1M',
    rating: 4.7,
    reviews: 1156,
    tags: ['Open-source', 'Powerful', 'Efficient', 'Popular'],
    capabilities: ['chat', 'code', 'reasoning'],
    category: 'language',
    isOpenSource: true,
    isNew: true,
    speed: 'fast',
    maxOutputTokens: 4096,
    createdAt: '2024-12-05T00:00:00Z',
  },
  {
    id: 'llama-3-1-405b',
    name: 'Llama 3.1 405B',
    provider: 'Meta',
    lab: 'Meta AI',
    description: 'Massive open-source model with exceptional capabilities.',
    contextWindow: '128K',
    priceInput: 4.25,
    priceOutput: 12.75,
    priceDisplay: '$4.25 / $12.75 per 1M',
    rating: 4.8,
    reviews: 892,
    tags: ['Massive', 'Open-source', 'Long-context', 'Powerful'],
    capabilities: ['chat', 'code', 'reasoning', 'analysis'],
    category: 'language',
    isOpenSource: true,
    isNew: false,
    speed: 'medium',
    maxOutputTokens: 8192,
    createdAt: '2024-07-23T00:00:00Z',
  },
  {
    id: 'llama-3-2-vision',
    name: 'Llama 3.2 Vision',
    provider: 'Meta',
    lab: 'Meta AI',
    description: 'Multimodal open-source model with vision understanding.',
    contextWindow: '8K',
    priceInput: 0.55,
    priceOutput: 0.75,
    priceDisplay: '$0.55 / $0.75 per 1M',
    rating: 4.6,
    reviews: 654,
    tags: ['Vision', 'Open-source', 'Multimodal', 'New'],
    capabilities: ['chat', 'vision', 'code'],
    category: 'multimodal',
    isOpenSource: true,
    isNew: false,
    speed: 'fast',
    maxOutputTokens: 4096,
    createdAt: '2024-09-24T00:00:00Z',
  },
  {
    id: 'llama-3-1-8b',
    name: 'Llama 3.1 8B',
    provider: 'Meta',
    lab: 'Meta AI',
    description: 'Lightweight open-source model for edge and mobile deployment.',
    contextWindow: '128K',
    priceInput: 0.05,
    priceOutput: 0.1,
    priceDisplay: '$0.05 / $0.10 per 1M',
    rating: 4.4,
    reviews: 521,
    tags: ['Lightweight', 'Edge', 'Fast', 'Open-source'],
    capabilities: ['chat', 'code'],
    category: 'language',
    isOpenSource: true,
    isNew: false,
    speed: 'fast',
    maxOutputTokens: 4096,
    createdAt: '2024-07-23T00:00:00Z',
  },

  // Mistral Models
  {
    id: 'mistral-large',
    name: 'Mistral Large',
    provider: 'Mistral',
    lab: 'Mistral AI',
    description: 'Most capable Mistral model with strong reasoning.',
    contextWindow: '32K',
    priceInput: 2.0,
    priceOutput: 6.0,
    priceDisplay: '$2.00 / $6.00 per 1M',
    rating: 4.7,
    reviews: 987,
    tags: ['Powerful', 'Reasoning', 'Enterprise', 'Capable'],
    capabilities: ['chat', 'code', 'reasoning'],
    category: 'language',
    isOpenSource: false,
    isNew: false,
    speed: 'medium',
    maxOutputTokens: 4096,
    createdAt: '2024-02-26T00:00:00Z',
  },
  {
    id: 'mistral-small',
    name: 'Mistral Small',
    provider: 'Mistral',
    lab: 'Mistral AI',
    description: 'Fast and efficient model for real-time applications.',
    contextWindow: '32K',
    priceInput: 0.14,
    priceOutput: 0.42,
    priceDisplay: '$0.14 / $0.42 per 1M',
    rating: 4.5,
    reviews: 645,
    tags: ['Fast', 'Efficient', 'Budget', 'Real-time'],
    capabilities: ['chat', 'code'],
    category: 'language',
    isOpenSource: false,
    isNew: false,
    speed: 'fast',
    maxOutputTokens: 4096,
    createdAt: '2024-02-26T00:00:00Z',
  },
  {
    id: 'mixtral-8x22b',
    name: 'Mixtral 8x22B',
    provider: 'Mistral',
    lab: 'Mistral AI',
    description: 'Mixture of experts model with 64K context window.',
    contextWindow: '64K',
    priceInput: 1.4,
    priceOutput: 4.2,
    priceDisplay: '$1.40 / $4.20 per 1M',
    rating: 4.6,
    reviews: 723,
    tags: ['MoE', 'Context', 'Efficient', 'Advanced'],
    capabilities: ['chat', 'code', 'reasoning'],
    category: 'language',
    isOpenSource: false,
    isNew: false,
    speed: 'medium',
    maxOutputTokens: 4096,
    createdAt: '2024-04-09T00:00:00Z',
  },
  {
    id: 'codestral',
    name: 'Codestral',
    provider: 'Mistral',
    lab: 'Mistral AI',
    description: 'Specialized model optimized for code generation and completion.',
    contextWindow: '32K',
    priceInput: 0.25,
    priceOutput: 0.75,
    priceDisplay: '$0.25 / $0.75 per 1M',
    rating: 4.7,
    reviews: 856,
    tags: ['Code', 'Specialized', 'Developer', 'Efficient'],
    capabilities: ['code', 'chat'],
    category: 'code',
    isOpenSource: false,
    isNew: false,
    speed: 'fast',
    maxOutputTokens: 4096,
    createdAt: '2024-03-25T00:00:00Z',
  },
  {
    id: 'mistral-nemo',
    name: 'Mistral Nemo',
    provider: 'Mistral',
    lab: 'Mistral AI',
    description: 'Lightweight model for edge deployment and mobile.',
    contextWindow: '16K',
    priceInput: 0.14,
    priceOutput: 0.42,
    priceDisplay: '$0.14 / $0.42 per 1M',
    rating: 4.4,
    reviews: 412,
    tags: ['Lightweight', 'Edge', 'Fast', 'Mobile'],
    capabilities: ['chat', 'code'],
    category: 'language',
    isOpenSource: true,
    isNew: false,
    speed: 'fast',
    maxOutputTokens: 4096,
    createdAt: '2024-07-02T00:00:00Z',
  },

  // DeepSeek Models
  {
    id: 'deepseek-v3',
    name: 'DeepSeek V3',
    provider: 'DeepSeek',
    lab: 'DeepSeek',
    description: 'Latest DeepSeek model with improved reasoning and efficiency.',
    contextWindow: '64K',
    priceInput: 0.27,
    priceOutput: 1.1,
    priceDisplay: '$0.27 / $1.10 per 1M',
    rating: 4.7,
    reviews: 834,
    tags: ['Efficient', 'Reasoning', 'Cost-effective', 'New'],
    capabilities: ['chat', 'code', 'reasoning'],
    category: 'language',
    isOpenSource: false,
    isNew: true,
    speed: 'fast',
    maxOutputTokens: 4096,
    createdAt: '2024-12-26T00:00:00Z',
  },
  {
    id: 'deepseek-r1',
    name: 'DeepSeek R1',
    provider: 'DeepSeek',
    lab: 'DeepSeek',
    description: 'Reasoning-focused model with strong analytical capabilities.',
    contextWindow: '64K',
    priceInput: 0.55,
    priceOutput: 2.19,
    priceDisplay: '$0.55 / $2.19 per 1M',
    rating: 4.8,
    reviews: 612,
    tags: ['Reasoning', 'Analysis', 'Powerful', 'New'],
    capabilities: ['reasoning', 'code', 'math'],
    category: 'language',
    isOpenSource: false,
    isNew: true,
    speed: 'medium',
    maxOutputTokens: 8192,
    createdAt: '2024-12-26T00:00:00Z',
  },
  {
    id: 'deepseek-coder-v2',
    name: 'DeepSeek Coder V2',
    provider: 'DeepSeek',
    lab: 'DeepSeek',
    description: 'Specialized coding model with exceptional programming capabilities.',
    contextWindow: '128K',
    priceInput: 0.27,
    priceOutput: 1.1,
    priceDisplay: '$0.27 / $1.10 per 1M',
    rating: 4.7,
    reviews: 521,
    tags: ['Code', 'Programming', 'Specialized', 'Efficient'],
    capabilities: ['code', 'chat', 'reasoning'],
    category: 'code',
    isOpenSource: true,
    isNew: false,
    speed: 'fast',
    maxOutputTokens: 4096,
    createdAt: '2024-06-14T00:00:00Z',
  },

  // Qwen Models
  {
    id: 'qwen-2-5-72b',
    name: 'Qwen 2.5 72B',
    provider: 'Qwen (Alibaba)',
    lab: 'Qwen',
    description: 'Large open-source model with strong performance across domains.',
    contextWindow: '128K',
    priceInput: 0.32,
    priceOutput: 0.64,
    priceDisplay: '$0.32 / $0.64 per 1M',
    rating: 4.6,
    reviews: 743,
    tags: ['Open-source', 'Powerful', 'Long-context', 'Versatile'],
    capabilities: ['chat', 'code', 'analysis'],
    category: 'language',
    isOpenSource: true,
    isNew: false,
    speed: 'medium',
    maxOutputTokens: 4096,
    createdAt: '2024-10-25T00:00:00Z',
  },
  {
    id: 'qwen-2-5-coder',
    name: 'Qwen 2.5 Coder',
    provider: 'Qwen (Alibaba)',
    lab: 'Qwen',
    description: 'Code-specialized model with excellent programming support.',
    contextWindow: '128K',
    priceInput: 0.32,
    priceOutput: 0.64,
    priceDisplay: '$0.32 / $0.64 per 1M',
    rating: 4.6,
    reviews: 591,
    tags: ['Code', 'Specialized', 'Programming', 'Open-source'],
    capabilities: ['code', 'chat'],
    category: 'code',
    isOpenSource: true,
    isNew: true,
    speed: 'fast',
    maxOutputTokens: 4096,
    createdAt: '2024-10-25T00:00:00Z',
  },
  {
    id: 'qwen-vl-plus',
    name: 'Qwen VL Plus',
    provider: 'Qwen (Alibaba)',
    lab: 'Qwen',
    description: 'Vision and language model with strong image understanding.',
    contextWindow: '32K',
    priceInput: 0.04,
    priceOutput: 0.16,
    priceDisplay: '$0.04 / $0.16 per 1M',
    rating: 4.5,
    reviews: 412,
    tags: ['Vision', 'Multimodal', 'Analysis', 'Efficient'],
    capabilities: ['chat', 'vision', 'analysis'],
    category: 'multimodal',
    isOpenSource: false,
    isNew: false,
    speed: 'fast',
    maxOutputTokens: 4096,
    createdAt: '2024-05-10T00:00:00Z',
  },

  // Cohere Models
  {
    id: 'command-r-plus',
    name: 'Command R Plus',
    provider: 'Cohere',
    lab: 'Cohere',
    description: 'Advanced model for enterprise search and generation with 128K context.',
    contextWindow: '128K',
    priceInput: 3.0,
    priceOutput: 15.0,
    priceDisplay: '$3.00 / $15.00 per 1M',
    rating: 4.6,
    reviews: 568,
    tags: ['Enterprise', 'Search', 'Long-context', 'Powerful'],
    capabilities: ['chat', 'search', 'code'],
    category: 'language',
    isOpenSource: false,
    isNew: false,
    speed: 'medium',
    maxOutputTokens: 4096,
    createdAt: '2024-03-28T00:00:00Z',
  },
  {
    id: 'command-r',
    name: 'Command R',
    provider: 'Cohere',
    lab: 'Cohere',
    description: 'Efficient model for enterprise search and text generation.',
    contextWindow: '128K',
    priceInput: 0.5,
    priceOutput: 1.5,
    priceDisplay: '$0.50 / $1.50 per 1M',
    rating: 4.5,
    reviews: 412,
    tags: ['Enterprise', 'Efficient', 'Search', 'Cost-effective'],
    capabilities: ['chat', 'search'],
    category: 'language',
    isOpenSource: false,
    isNew: false,
    speed: 'fast',
    maxOutputTokens: 4096,
    createdAt: '2024-03-28T00:00:00Z',
  },
  {
    id: 'aya-23',
    name: 'Aya 23',
    provider: 'Cohere',
    lab: 'Cohere',
    description: 'Open-source multilingual model supporting 23 languages.',
    contextWindow: '8K',
    priceInput: 0.0,
    priceOutput: 0.0,
    priceDisplay: 'Free (open-source)',
    rating: 4.4,
    reviews: 287,
    tags: ['Open-source', 'Multilingual', 'Community', 'Free'],
    capabilities: ['chat'],
    category: 'language',
    isOpenSource: true,
    isNew: false,
    speed: 'fast',
    maxOutputTokens: 4096,
    createdAt: '2024-02-14T00:00:00Z',
  },

  // xAI Models
  {
    id: 'grok-2',
    name: 'Grok-2',
    provider: 'xAI',
    lab: 'xAI',
    description: 'Advanced model with real-time reasoning and multimodal capabilities.',
    contextWindow: '128K',
    priceInput: 2.0,
    priceOutput: 10.0,
    priceDisplay: '$2.00 / $10.00 per 1M',
    rating: 4.7,
    reviews: 634,
    tags: ['Reasoning', 'Real-time', 'Advanced', 'Humorous'],
    capabilities: ['chat', 'reasoning', 'code'],
    category: 'language',
    isOpenSource: false,
    isNew: true,
    speed: 'fast',
    maxOutputTokens: 4096,
    createdAt: '2024-12-01T00:00:00Z',
  },
  {
    id: 'grok-2-vision',
    name: 'Grok-2 Vision',
    provider: 'xAI',
    lab: 'xAI',
    description: 'Multimodal version with vision understanding capabilities.',
    contextWindow: '128K',
    priceInput: 2.5,
    priceOutput: 12.5,
    priceDisplay: '$2.50 / $12.50 per 1M',
    rating: 4.6,
    reviews: 512,
    tags: ['Vision', 'Multimodal', 'Advanced', 'New'],
    capabilities: ['chat', 'vision', 'reasoning'],
    category: 'multimodal',
    isOpenSource: false,
    isNew: true,
    speed: 'fast',
    maxOutputTokens: 4096,
    createdAt: '2024-12-01T00:00:00Z',
  },
  {
    id: 'grok-beta',
    name: 'Grok Beta',
    provider: 'xAI',
    lab: 'xAI',
    description: 'Beta version with experimental features and improvements.',
    contextWindow: '128K',
    priceInput: 1.5,
    priceOutput: 7.5,
    priceDisplay: '$1.50 / $7.50 per 1M',
    rating: 4.5,
    reviews: 289,
    tags: ['Beta', 'Experimental', 'Advanced', 'Testing'],
    capabilities: ['chat', 'reasoning'],
    category: 'language',
    isOpenSource: false,
    isNew: true,
    speed: 'fast',
    maxOutputTokens: 4096,
    createdAt: '2024-11-15T00:00:00Z',
  },

  // Stability Models
  {
    id: 'stable-diffusion-xl',
    name: 'Stable Diffusion XL',
    provider: 'Stability AI',
    lab: 'Stability AI',
    description: 'Advanced image generation model with superior quality.',
    contextWindow: '2K',
    priceInput: 0.04,
    priceOutput: 0.12,
    priceDisplay: '$0.04 / $0.12 per 1M',
    rating: 4.7,
    reviews: 1542,
    tags: ['Image', 'Generation', 'Quality', 'Popular'],
    capabilities: ['image', 'creative'],
    category: 'image',
    isOpenSource: true,
    isNew: false,
    speed: 'medium',
    maxOutputTokens: 2048,
    createdAt: '2023-07-26T00:00:00Z',
  },
  {
    id: 'stable-video',
    name: 'Stable Video',
    provider: 'Stability AI',
    lab: 'Stability AI',
    description: 'Text-to-video generation model for creating animated content.',
    contextWindow: '4K',
    priceInput: 0.08,
    priceOutput: 0.24,
    priceDisplay: '$0.08 / $0.24 per 1M',
    rating: 4.5,
    reviews: 421,
    tags: ['Video', 'Generation', 'Creative', 'New'],
    capabilities: ['image', 'video'],
    category: 'image',
    isOpenSource: false,
    isNew: false,
    speed: 'slow',
    maxOutputTokens: 2048,
    createdAt: '2024-04-25T00:00:00Z',
  },

  // ElevenLabs Models
  {
    id: 'eleven-multilingual-v2',
    name: 'Eleven Multilingual v2',
    provider: 'ElevenLabs',
    lab: 'ElevenLabs',
    description: 'Advanced text-to-speech with natural voice generation in 29 languages.',
    contextWindow: '32K',
    priceInput: 0.015,
    priceOutput: 0.015,
    priceDisplay: '$0.015 per 1M',
    rating: 4.8,
    reviews: 2143,
    tags: ['Audio', 'Voice', 'Multilingual', 'Natural'],
    capabilities: ['audio', 'speech'],
    category: 'audio',
    isOpenSource: false,
    isNew: false,
    speed: 'fast',
    maxOutputTokens: 8192,
    createdAt: '2024-06-05T00:00:00Z',
  },
  {
    id: 'eleven-turbo-v2',
    name: 'Eleven Turbo v2',
    provider: 'ElevenLabs',
    lab: 'ElevenLabs',
    description: 'High-speed text-to-speech for real-time voice applications.',
    contextWindow: '32K',
    priceInput: 0.015,
    priceOutput: 0.015,
    priceDisplay: '$0.015 per 1M',
    rating: 4.7,
    reviews: 1456,
    tags: ['Audio', 'Voice', 'Real-time', 'Fast'],
    capabilities: ['audio', 'speech'],
    category: 'audio',
    isOpenSource: false,
    isNew: false,
    speed: 'fast',
    maxOutputTokens: 8192,
    createdAt: '2024-08-10T00:00:00Z',
  },

  // Additional diverse models for completeness
  {
    id: 'perplexity-sonar-pro',
    name: 'Perplexity Sonar Pro',
    provider: 'Perplexity',
    lab: 'Perplexity AI',
    description: 'Web-connected model with real-time search and analysis.',
    contextWindow: '200K',
    priceInput: 3.0,
    priceOutput: 15.0,
    priceDisplay: '$3.00 / $15.00 per 1M',
    rating: 4.6,
    reviews: 743,
    tags: ['Search', 'Real-time', 'Web', 'Analysis'],
    capabilities: ['chat', 'search', 'reasoning'],
    category: 'language',
    isOpenSource: false,
    isNew: false,
    speed: 'medium',
    maxOutputTokens: 4096,
    createdAt: '2024-10-12T00:00:00Z',
  },
  {
    id: 'together-ai-meta-llama',
    name: 'Together AI Llama',
    provider: 'Together AI',
    lab: 'Together AI',
    description: 'Hosted Llama models with optimized inference.',
    contextWindow: '128K',
    priceInput: 0.2,
    priceOutput: 0.6,
    priceDisplay: '$0.20 / $0.60 per 1M',
    rating: 4.5,
    reviews: 512,
    tags: ['Hosted', 'Llama', 'Optimized', 'Open-source'],
    capabilities: ['chat', 'code'],
    category: 'language',
    isOpenSource: true,
    isNew: false,
    speed: 'fast',
    maxOutputTokens: 4096,
    createdAt: '2024-08-15T00:00:00Z',
  },
  {
    id: 'dbrx',
    name: 'DBRX',
    provider: 'Databricks',
    lab: 'Databricks',
    description: 'Open-source mixture of experts model optimized for enterprises.',
    contextWindow: '32K',
    priceInput: 0.6,
    priceOutput: 1.8,
    priceDisplay: '$0.60 / $1.80 per 1M',
    rating: 4.5,
    reviews: 387,
    tags: ['MoE', 'Enterprise', 'Open-source', 'Optimized'],
    capabilities: ['chat', 'code'],
    category: 'language',
    isOpenSource: true,
    isNew: false,
    speed: 'fast',
    maxOutputTokens: 4096,
    createdAt: '2024-03-27T00:00:00Z',
  },
];
